### ISSUE TITLE
Need to sort keys when json.dumps'ing a dict to string, helps with comparison

### ISSUE THREAD

**Issue by stevenchamales** [trustar/trustar-python#51]
https://github.com/trustar/trustar-python/blob/fdce467834cd659ac45290d6fa7f8b01a0773fb9/trustar/models/base.py#L42

We should add the "sort_keys=True" argument to the json.dumps() call.  This way, if I want to compare 2 Indicator objects, I can use   str(indicator_one) == str(indicator_two) and know that the object is going to be converted to a dictionary with empty keys omitted from the dictionary, then the dictionary will be dumped to a string, with keys in the same order.  So if two Indicator objects have the same values for the same attributes, they should dump to precisely the same string.  I can then use that for comparison, or for de-duplicating lists of indicators. 

-Steve

**Comment by michaelknopf** [comment]
Sure, go for it @stevenchamales

**Comment by stevenchamales** [comment]
Thx!

On Feb 27, 2019, at 10:40 AM, Michael Knopf <notifications@github.com> wrote:

Sure, go for it @stevenchamales
