### ISSUE TITLE
"get_indicators" - DB timeouts  & time window chunking

### ISSUE THREAD

**Issue by stevenchamales** [trustar/trustar-python#56]
Large requests to the /1.3/indicators endpoint that take Neo a long time to process will timeout., causing calls to the "get_indicator" method to fail with a 500 error.  It's high time we make this method automatically break large time windows or undefined time windows into smaller time windows, and it should be able to sense errors due to DB timeout and handle them by further splitting the time window and retrying the call in 2 pieces until it either works or has split 3 times to no avail. 3 is arbitrary - we need to limit it somehow / make sure there's a base-case that it will always arrive at in a reasonable amount of time. 

https://github.com/trustar/trustar-python/blob/707d51adc58d68aed7de12a4ca37949cb75cf122/trustar/indicator_client.py#L57

**Comment by michaelknopf** [comment]
That's something that belongs in a wrapper library, not inside the SDK.  Again, the SDK is a light wrapper around the requests library.  Anything beyond that needs to go either directly in the client program, or in a separate library.

Here's the deeper explanation:
The performance issue is something that needs to be fixed within the API, not in the SDK.  With things like this, there are a number of different ways to handle them on the client side.  If you put one of these ways into the SDK, it becomes _coupled_ to that solution: client programs cannot opt out of that decision if it does not suit their use case.  This makes the SDK _opinionated_.  If something makes an arbitrary choice that cannot be easily bypassed, it is by definition opinionated.  The SDK must be an unopinionated library (we can discuss why another time).  So any logic like this belongs in a separate library.
