### ISSUE TITLE
default page_size should be 1000.  

### ISSUE THREAD

**Issue by stevenchamales** [trustar/trustar-python#58]
Because the API endpoint defaults to page size of 100, and it's annoyingly slow. 

https://github.com/trustar/trustar-python/blob/707d51adc58d68aed7de12a4ca37949cb75cf122/trustar/indicator_client.py#L59

**Comment by michaelknopf** [comment]
Just pass 1000 if you want it to be 1000.

**Comment by stevenchamales** [comment]
I always pass 1000.  Integrations don’t, and customers writing their own scripts don’t.
