### ISSUE TITLE
Random pong is returned

### ISSUE THREAD

**Issue by DavidHazaniInt** [trustar/trustar-python#62]
why ping did not return 'pong' as docs spec?
![Screenshot from 2019-11-25 17-42-37](https://user-images.githubusercontent.com/49366909/69554862-1424c600-0fab-11ea-9247-89ac8104af51.png)

**Comment by dsolmirano** [comment]
Thanks for bringing this to our attention. This code needs to be fixed on the other end of the API. I'll keep you posted

**Comment by dsolmirano** [comment]
This has been fixed with our latest internal code release. Thanks!
