### ISSUE TITLE
Adds invalid field to the API call's JSON body. 

### ISSUE THREAD

**Issue by stevenchamales** [trustar/trustar-python#65]
https://github.com/trustar/trustar-python/blob/81b96849aefd7978fe8f2233fc0e8b9e26f6d368/trustar/indicator_client.py#L52

@michaelknopf ,  When using this method, if I have tags on each indicator object that I want applied to those indicators, then when it dumps an indicator to dict, the indicator's tags get dumped to dict and the 'id' key is in those tag dicts.  

Then that indicator dict's "tags" key has a value that is a list of tag dicts that all have the "id" key.  

The tag's ID key, per the documentation for the endpoint used by this method, is not a key that is expected to be present in the API call.  Will its presence cause the API call to fail?

-Steve

**Comment by michaelknopf** [comment]
No, it's fine.
