### ISSUE TITLE
add "typing" library for Python  2  compatibility

### ISSUE THREAD

**Issue by stevenchamales** [trustar/trustar-python#88]
https://github.com/trustar/trustar-python/blob/e5150cd1ee658f9f3c96bb5583f053739d0d0de0/setup.py#L30

typing library is now used in report_client.py:
https://github.com/trustar/trustar-python/commit/6977b2575d9df10d6f44dcf8c639fbd493d830d0#r44227254

typing was added to stdlib  in 3.5:
<img width="634" alt="Screen Shot 2020-11-16 at 8 09 10 AM" src="https://user-images.githubusercontent.com/12991420/99277738-03d0b100-27e3-11eb-850a-556e5e1017aa.png">

recommend  add "typing" to "install_requires".

**Comment by chrisinmtown** [comment]
Python 2 went end of life on 1 Jan 2020.  You really want to put time & effort into support for an EOL system?

https://www.python.org/doc/sunset-python-2/
