### ISSUE TITLE
Extend ReportClient API to get multiple report details in single HTTP request

### ISSUE THREAD

**Issue by chrisinmtown** [trustar/trustar-python#91]
Extend the ReportClient API so a client can get report details for multiple IDs, either by extending the get_report_details method or by adding a new method.

ReportClient has method `get_report_details` that accepts a single report ID:

https://github.com/trustar/trustar-python/blob/e5150cd1ee658f9f3c96bb5583f053739d0d0de0/trustar/report_client.py#L27

Why? I am trying to cope with HTTP request rate limiting in the TruStar server.  I have a list of report IDs from search results. It seems inefficient to make a separate HTTP request for each one, since reports are only a few K bytes in size. 

Design considerations:
* should the method allow a mix of internal and external IDs, or should they all be the same type?
* the new method should enforce an upper limit on the ID list size, it's not reasonable to ask for a million
* the result must indicate the outcome for each request ID; i.e., success (and data), fail (and reason); maybe denied (if too many)
* probably requires a new server endpoint

Thanks for considering it.

**Comment by chrisinmtown** [comment]
Does anyone at Trustar monitor these issues?  15 days without a response so far.

**Comment by stevenchamales** [comment]
@chrisinmtown, all feature requests should come through the TruSTAR employee who serves as the account manager for the company you're working on behalf of.  

Regards, 
- Steve

**Comment by chrisinmtown** [comment]
I'm confused by this response. Is this open-source or closed source?
